//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEditor.CustomEditor(typeof(ColorEvent))]
    public class ColorInspector : lisandroct.EventSystem.EventInspector<UnityEngine.Color, ColorTest> {
    }
    
    public class ColorTest : lisandroct.EventSystem.TestObject<UnityEngine.Color> {
    }
}
